### ISSUE TITLE
Roar gem not found 

### ISSUE THREAD

**Issue by gregd** [apotonick/gemgem-trbrb#13]
In Gemfile the Roar gem version is defined as
`gem "roar", path: "../roar" #"1.0.0"`
which causes 
`The path `/home/greg/examples/roar` does not exist.`
when bundler is run.

I've tired to fix that by removing the path, so bundler could resolve dependency (to 1.0.3). However there were some errors during app startup.

**Comment by apotonick** [comment]
```ruby
gem roar, github: "apotonick/roar"
```

Will push Roar 1.1 soon.
