### ISSUE TITLE
Classes cacheing issue?

### ISSUE THREAD

**Issue by kevinansfield** [apotonick/gemgem-trbrb#7]
I'm seeing an odd issue in my tests and when running the site - the `classes` variable seems to be cached somewhere such that on each subsequent call/refresh the `end` class gets added on again.

Do you have any idea why that might be happening?

![screen shot 2015-05-29 at 10 07 30](https://cloud.githubusercontent.com/assets/415/7879695/96a3916c-05ea-11e5-8900-55cdf589c5d4.png)

**Comment by kevinansfield** [comment]
Changing the `classes` method in `Cell::GridCell` so that it duplicates the class variable seems to fix it:

```
def classes
  classes = self.class.classes.dup
  classes << 'end' if options[:last] == model
  classes
end
```

**Comment by apotonick** [comment]
Hey, @kevinansfield thanks man! I already fixed it in https://github.com/apotonick/gemgem-trbrb/blob/chapter-7/app/trb/cell/grid_cell.rb#L15 but I need to clean that up in the book, too! Thanks for reminding me!

**Comment by kevinansfield** [comment]
Cool. Just finished the book so far, looking forward to reading the rest of it as it arrives! Thanks for writing it :)

Now I'm off to see how I get on converting my current project over to the Trailblazer-Way...
